config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum:6, maximum:100 }
    validates :description, presence: true, length: { minimum:10, maximum:2000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 30 }
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: {minimum: 3, maximum: 25}
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 40}, 
                      format: { with: VALIDATE_EMAIL_REGEX }
  has_secure_password                   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_login
      if !logged_in?
        flash[:alert] = "You must log in to perform this action"
        redirect_to login_path
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, only: [:show, :edit, :update, :destroy]
    before_action :require_login, except: [:show, :index]
    before_action :require_user_permissions, only: [:edit, :update, :destroy]

    def show
        
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 4)
    end

    def new
        @article = Article.new  #creates empty initialization to prevent error
    end

    def edit
        
    end

    def create
        @article = Article.new(validateParams)
        @article.user = current_user
        if @article.save
          flash[:notice] = "Your article has been created and saved." #flash hash message notices and alerts will appear within the body template of the app html
          redirect_to @article
        else
          render 'new'
        end
    end

    def update
        
        if @article.update(validateParams)
            flash[:notice] = "Your article has been updated."
            redirect_to @article
        else
          render 'edit'
        end
    end

    def destroy
        
        @article.destroy
        redirect_to articles_path
    end

    private

    def find_article
      @article = Article.find(params[:id])
    end

    def validateParams
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_user_permissions
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You do not have permission to edit or delete another user's article."
        redirect_to @article
      end
    end

end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:show, :index] 
    
    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "The category has been successfully created."
        redirect_to @category
      else
        render 'new'
      end
    end

    def show
      @category = Category.find(params[:id])
      @articles = @category.articles.paginate(page: params[:page], per_page: 2)
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 6)
        
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category= Category.find(params[:id])
      if @category.update(category_params)
        flash[:notice] = "Category name update - success."
        redirect_to @category
      else
        render 'edit'
      end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
      if !(logged_in? && current_user.admin?)
        flash[:alert] = "You do not have permission to perform this action -Admin"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to articles_path if logged_in?
    end
    
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user =User.find_by(email: params[:session] [:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Login Successful"
            redirect_to user
        else
            flash.now[:alert] = "Your login details were incorrect "
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged Out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update, :destroy]
  before_action :require_login, only: [:edit,:update]
  before_action :require_user_permissions, only: [:edit,:update, :destroy]

  def show 
    # @user = User.new(user_params)
    @articles = @user.articles.paginate(page: params[:page], per_page: 4)
  end
  
  def index
    @users = User.paginate(page: params[:page], per_page: 6)
  end

  def new
    @user = User.new
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account has been updated."
      redirect_to @user
    else
      render 'edit'
    end
  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]= @user.id
      flash[:notice] = "Thanks for signing up #{@user.username}! Welcome."
      redirect_to articles_path
    else
        render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "This account and associated articles have been deleted."
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_user_permissions
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options= { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded float-right d-block shadow-sm")
    end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="row justify-content-center">
  <div class="col-10">
  <%= render 'shared/errormsg', objer: @article %>
    <%= form_with(model: @article, class: "shadow mb-4 p-5 bg-white rounded", local: true) do |form| %>
      <div class="form-group row">
        <%= form.label :title, class: "col-2 col-form-label" %>
        <div class="col-10">
        <%= form.text_field :title, class: "form-control shadow-sm mb-4 p-3 bg-white rounded" %>
        </div>
      </div>
    
      <div class="form-group row">
        <%= form.label :description, class: "col-2 col-form-label" %>
        <div class="col-10">
        <%= form.text_area :description, rows: 10, class: "form-control shadow-sm mb-4 p-3 bg-white rounded" %>
        </div>
      </div>
      <div class="form-group row mb-0">
        <%= form.label :category, class: "col-2 col-form-label" %>
        <div class="col-10">
        <%= form.collection_select(:category_ids, Category.all, :id, :name,
        { prompt: "<< -- Optional Category Selection -- >>"},{ multiple: true, size: 4, class: "custom-select mb-3 shadow-sm rounded" }) %>
        <hr />
        </div>
      </div>

      <div class="form-group row justify-content-end"> 
          <%= form.submit class: "btn text-white mysecondary btn-lg" %>
      </div>

      <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div id="altbg">
  <div class="container my-5">
    <h1 class="display-4">Edit Article</h1>
    <p><small><strong>Author:</strong> <em><%= @article.user.username %> </em></small></p>
      <br />
      <br/>
    <%= render 'form' %>

    <hr />
    <%= link_to '<< Back To List', articles_path, class:"mydarktext" %> | 
    <%= link_to 'Delete', article_path(@article), class:"mydarktext", data: {confirm: "Confirm you want to delate this article!"} %> 
  </div>
</div>

app/views/articles/index.html.erb
<div id="altbg">
  <div class="container-xl mt-4">
    <h1 class="display-4">List of Articles</h1>
    <br/>

    <div class="row">
    <% random_num = 1 %>
      <% @articles.each do |article| %>
      <div class="col-xl-3 col-lg-4 col-sm-6">
        <div class="card shadow mb-5 bg-white rounded">
          <div class="card-body text-center">
            <h5 class="card-title">
              <%= link_to article.title, article_path(article), class:"text-dark"%>
            </h5>
            <%= image_tag("https://picsum.photos/200?random=#{random_num}") %>
            
            <br />

            <small><strong>Author:</strong> <em><%= link_to article.user.username, user_path(article.user) %> </em></small> 
            <br />
            <p class="card-text">

            </p>
            
            <%= link_to 'VIEW', article_path(article), class: "btn btn-sm text-white mysand" %> 
            
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'EDIT', edit_article_path(article), class: "btn btn-sm btn-dark" %> 
              <%= link_to 'DELETE', article_path(article), method: :delete, data: {confirm: "Confirm you want to delate this article!"}, class:"btn btn-sm text-white mysecondary" %>  
            <% end %>
          </div>

          <div class="card-footer text-white mydark text-center">
            <em>Created: <%= time_ago_in_words(article.created_at) %> ago.</em><br/>
            <% if article.categories.any? %>
              <div class="my-1"><%= render article.categories %><br/></div>
            <% end %>
              
          </div>
        </div>
      </div>
      <% random_num = random_num + 1 %> 
    <% end %>
    </div>
    <div class="pagination justify-content-center p-3 mb-3">
      <%= will_paginate @articles, :container => false %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div id="altbg">
    <div class="container my-5">
        <h1 class="display-4">Create New Article</h1>
        <br/>

        <%= render 'form' %>

    </div>
</div>

app/views/articles/show.html.erb
<div id="altbg">

<div class="hero">
  <h1 class="other"><%= @article.title %></h1> <br /> </p>
  <p class="auth_img"><%= link_to gravatar_for(@article.user), user_path(@article.user) %>
  <p class="auth_ctr"><strong>Author:</strong> <em><%= @article.user.username %> </em></small></p>
</div>

<div class="container-fluid px-5">
  <div class="card shadow mb-5 mt-n4 bg-white rounded">
    <div class="card-body">
    <% if @article.categories.any? %>
      <div class="mb-2 text-center"><%= render @article.categories %></div>
    <% end %>
    <hr class="px-3" />
      <div class="card-text">
        <%= simple_format(@article.description) %>
      </div> 

      <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
        <%= link_to 'EDIT', edit_article_path(@article), class: "btn btn-sm btn-dark" %> 
        <%= link_to 'DELETE', article_path(@article), method: :delete, data: {confirm: "Confirm you want to delate this article!"}, class:"btn btn-sm text-white mysecondary" %>
      <% end %> 
    </div>
    <div class="card-footer text-white mydark text-center">
      <em>Created: <%= time_ago_in_words(@article.created_at) %> ago.</em> | <strong> Updated: <%= time_ago_in_words(@article.updated_at) %> ago.</strong>
    </div>
  </div>
    
</div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-dark mysand mb-1" %> &nbsp;

app/views/categories/edit.html.erb
<div id="altbg">
    <div class="container my-5">
        <h1 class="display-4">Edit Category Name</h1>
        <br/>

        <div class="row justify-content-center">
          <div class="col-10">
            <%= render 'shared/errormsg', objer: @category %>
            <%= form_with(model: @category, class: "shadow mb-4 p-5 bg-white rounded", local: true) do |form| %>
              <div class="form-group row">
                <%= form.label :name, "Category Name", class: "col-2 col-form-label" %>
                <div class="col-10">
                  <%= form.text_field :name, class: "form-control shadow-sm mb-4 p-3 bg-white rounded", placeholder: "Enter a category name" %>
                </div>
              </div>
          <div class="form-group row justify-content-end"> 
            <%= form.submit class: "btn text-white mysecondary btn-lg" %>
          </div>

          <% end %>
          </div>
        </div>
    </div>
    
        
</div>

app/views/categories/index.html.erb
<div id="altbg">
  <div class="container-xl mt-4">
    <h1 class="display-4">Category List</h1>
    <br/>
    <div class="row">
      <% random_num = 1 %>
      <% @categories.each do |category| %>

      <div class="col-lg-6">
        <div class="card mb-3 card shadow bg-white rounded">
          <div class="row">

            <div class="col-md-4 col-sm-6 cat-bgimg">
              
            </div>

            <div class="col-md-8">
              <div class="card-body px-3">
                <h5 class="card-title">
                  <%= link_to category.name, category_path(category), class:"text-dark"%>
                </h5>
                <p class="card-text">Hard code category Description for now </p>
                <p class="card-text"><small class="text-muted">Article Count: <%= category.articles.count %><br /> Category Created: <%= time_ago_in_words(category.created_at) %> ago.</small></p>
              </div>
            </div>

          </div>
        </div>
      </div>
      <% random_num = random_num + 1 %> 
      <% end %>
    </div>

    <div class="pagination justify-content-center p-3 mb-3">
      <%= will_paginate @categories, :container => false %>
    </div>

  </div>
</div>

app/views/categories/show.html.erb
<div id="altbg">
  <div class="hero">
    <h1 class="other"><%= @category.name %></h1> <br />
    
  </div>
  <div class="container-fluid px-5">
    <div class="card shadow mb-5 mt-n5 bg-white rounded">
      <div class="card-body">
        <div class="card-text">
          <h6 class="mysand-text"> Article Count: <%= @category.articles.count %></h6>
          <hr />
          <p><strong>Hard code Category Description </strong> - Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Sed facilisis justo sit amet eros varius dapibus. Proin ligula augue, luctus suscipit dui in, 
          hendrerit luctus. Fusce leo quam, sollicitudin ut quam vitae, vehicula finibus mi. 
          Fusce rhoncus enim eget leo viverra, quis fringilla ipsum tempor. Aenean tempor massa a tellus suscipit, 
          vel elementum ligula pulvinar. </p>

          <p>Wanec hendrerit ipsum quis ligula vestibulum cursus. Fusce ullamcorper ipsum a risus hendrerit gravida. 
          Curabitur eget magna vulputate, fermentum lorem sed, hendrerit nisi. Nulla sit amet sollicitudin magna. 
          Donec diam metus, posuere eu interdum luctus, fringilla vel libero.</p>
        </div> 
        
        <%= link_to 'BACK TO CATEGORIES', categories_path, class: "btn btn-sm mysand btn-dark float-right " %> 
        <% if logged_in? && current_user.admin? %>
          <%= link_to "EDIT CATEGORY", edit_category_path(@category), class: "btn btn-sm btn-dark float-right mx-1" %>
        <% end %>
          
        
      </div>

      <div class="card-footer text-white mydark text-center">
        <em>Created: <%= time_ago_in_words(@category.created_at) %> ago.</em> | <strong> Updated: <%= time_ago_in_words(@category.updated_at) %> ago.</strong>
      </div>
    </div>
  </div>

  <div class="container-fluid px-5">
    <div class="pagination justify-content-center p-3 mb-3">
      <%= will_paginate @articles, :container => false %>
    </div>

    <div class="row">
    <% random_num = 1 %>
      <% @category.articles.each do |article| %>
      <div class="col-lg-6">
        <div class="card shadow mb-4 bg-white rounded text-center">     
          <div class="card-body">
          
          <%= image_tag("https://picsum.photos/350/200?random=#{random_num}&blur=2") %> <br />
            <h5 class="card-title m-3">
                <%= link_to article.title, article_path(article), class:"text-dark" %>
            </h5>
            <small>
              <strong>Author:</strong> <em><%= article.user.username %> </em>
            </small> 
            
            <br />

            <p class="card-text">
              <%= truncate(article.description, length: 75) %>
            </p>
                
            <%= link_to 'VIEW', article_path(article), class: "btn text-white mysand" %> 
            <% if logged_in? && article.user == current_user %>
              <%= link_to 'EDIT', edit_article_path(article), class: "btn btn-dark" %> 
              <%= link_to 'DELETE', article_path(article), method: :delete, data: {confirm: "Confirm you want to delate this article!"}, class:"btn text-white mysecondary" %>
            <% end %>  
          </div>

          <div class="card-footer text-white mydark text-center">
            <em>Created: <%= time_ago_in_words(article.created_at) %> ago.</em>
          </div>

        </div>
      </div>  
      <% random_num = random_num + 1 %>      
      <% end %>

    </div>
    
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 text-white">
  <div class="container text-center">
    <small>COPYRIGHT &copy; MCKIM BLOG 2021</small>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-light">

<%= link_to "TRAVEL SANCTUARY", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto"
    
    <li class="nav-item">
    <%= link_to "Authors", users_path, class: "nav-link" %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if logged_in? && current_user.admin %>
          <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
        <% end %>
        <%= link_to "Category List", categories_path, class: "dropdown-item" %>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Articles
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if logged_in? %>
          <%= link_to "Create New Article", new_article_path, class: "dropdown-item" %>
        <% end %>
        <%= link_to "Article List", articles_path, class: "dropdown-item" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "(Admin)" if current_user.admin? %> <%= current_user.username %> Profile 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Delete Profile", user_path(current_user), method: :delete, class: "dropdown-item text-danger", data: { confirm: "Are you sure you want to delete your account?"} %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
        <li class="nav-item ">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item ">
          <%= link_to "Sign Up", signup_path, class: "nav-link" %>
        </li>
    <% end %>
    
  </ul>
  
</div>
</nav>

app/views/pages/about.html.erb
<h1>This will be a user profile page</h1>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container-fluid">
    <div class="jumbotron text-center p-5 mt-5">
      <div class="my-5">
        <h1 class="display-4">The Travel Sanctuary</h1>

        <hr class="col-3 justify-content-center my-3">
        <p class="h4">Sharing experiences<br />and outdoor adventures!</p>
<br />
<%= link_to "Login", login_path, class: "btn btn-secondary btn-lg" %>
<%= link_to "Sign Up", signup_path, class: "btn btn-light btn-lg", id: "login" %>
    </div>
    </div>
    
  </div>
  <div class="welcome py-5 mb-3"> </div>
</div>

app/views/users/edit.html.erb
<div id="altbg">
    <div class="container my-5">
        <h1 class="display-4">Edit Your Profile</h1>
        <br/>

        <%= render 'form' %>

    
        <hr />
        <%= link_to '<< Back To List', articles_path, class:"mydarktext" %> 
    </div>
</div>

app/views/users/index.html.erb
<div id="altbg">
  <div class="container my-5">  
    <div class="card mb-4 shadow">
      <div class="row no-gutters">
        <div class="col">
          <div class="card-body">
          <div class ="col-lg"><h5 class="display-4">OUR MEMBERS</h5></div>
            <div class="d-flex flex-row align-content-start flex-wrap">
              <div class="col-xs mb-1"><%= image_tag("img_avatar6.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar4.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar3.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar5.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar4.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar3.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar6.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar2.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar6.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar3.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar5.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar4.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar3.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar5.png", size: "67", alt: "user") %>&nbsp;</div>
              <div class="col-xs mb-1"><%= image_tag("img_avatar4.png", size: "67", alt: "user") %></div>
            </div>

          </div>
        </div>
      </div>
    </div>


    <div class="row">
      <% @users.each do |user| %>

      <div class="col-lg-4 col-md-6">

        <div class="card shadow mb-4 bg-white rounded">

          <div class="card-body text-center">
            <h3><%= link_to user.username, user, class: "mysand-text" %></h3>
            <hr class="col-1 my-3" />
            <h5 class="card-title float-right">
              <%= link_to gravatar_for(user, size:125), user %>
            </h5>

            <p class="card-text">Article count: <%= user.articles.count %> </p> 
          
	          <%= link_to "View Profile", user, class: "btn text-white mysand mb-1" %> <br />
            <% if logged_in? %>
              <% if user == current_user %>       
                <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-dark mb-1" %> <br />
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete User", user_path(user), class: "btn btn-danger", 
                method: :delete, data: { confirm: "Are you sure you want to delete the user and all of their articles?"} %>
              <% end %>


            <% end %>
          </div>

          <div class="card-footer text-white mydark text-center">
            <p><strong><%= user.username %></strong> <em>Joined: <%= time_ago_in_words(user.created_at) %> ago.</em></p>
          </div>

        </div>

      </div>
      <% end %>

    </div>

    <div class="pagination justify-content-center p-3 mb-3">
      <%= will_paginate @articles, :container => false %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div id="altbg">
  <div class="container my-5">  
    <div class="card mb-4">
      <div class="row no-gutters">
        <div class="col-md-4 p-3">
          <%= gravatar_for @user, size:190, class: "float-right" %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="display-4">
              <%= @user.username %>'s Profile
            </h5>
            <h4 class="mysand-text">
              <%= @user.username %>'s <span class="lead"> Article Count: 
              <%= @user.articles.count %> </span>
            </h4>
            <p class="card-text">
              This is a wider card with supporting text.
            </p>
            <p class="card-text"><small class="text-muted">MEMBER SINCE: <%= time_ago_in_words(@user.created_at) %> ago.</small>
            </p>
          </div>
        </div>
      </div>

      <div class="card-footer text-white bg-transparent text-center px-5">
        <div class="row justify-content-center">
          <div class="pagination mb-3">
            <%= will_paginate @articles, :container => false %>
          </div>
        </div>      
      </div>

    </div>

    <div class="row">
    <% random_num = 1 %>
      <% @articles.each do |article| %>
      <div class="col-lg-6">
        <div class="card shadow mb-4 bg-white rounded text-center">     
          <div class="card-body">
          
          <%= image_tag("https://picsum.photos/415/200?random=#{random_num}&blur=2") %> <br />
            <h5 class="card-title m-3">
                <%= link_to article.title, article_path(article), class:"text-dark" %>
            </h5>
            <small>
              <strong>Author:</strong> <em><%= article.user.username %> </em>
            </small> 
            
            <br />

            <p class="card-text">
              <%= truncate(article.description, length: 75) %>
            </p>
                
            <%= link_to 'VIEW', article_path(article), class: "btn text-white mysand" %> 
            <% if logged_in? && article.user == current_user %>
              <%= link_to 'EDIT', edit_article_path(article), class: "btn btn-dark" %> 
              <%= link_to 'DELETE', article_path(article), method: :delete, data: {confirm: "Confirm you want to delate this article!"}, class:"btn text-white mysecondary" %>
            <% end %>  
          </div>

          <div class="card-footer text-white mydark text-center">
            <em>Created: <%= time_ago_in_words(article.created_at) %> ago.</em>
          </div>

        </div>
      </div>  
      <% random_num = random_num + 1 %>      
      <% end %>

    </div>

  </div>
</div>